CREATE TABLE todo_items (
	id INT PRIMARY KEY AUTO_INCREMENT COMMENT '待办事项ID',
	task_name VARCHAR(255) NOT NULL COMMENT '任务名',
	due_time DATETIME NOT NULL COMMENT '时间',
	priority ENUM('Low', 'Medium', 'High') DEFAULT 'Medium' COMMENT '优先级',
	notes TEXT COMMENT '备注',
	is_completed BOOLEAN DEFAULT false COMMENT '完成状态',
	create_by VARCHAR(100) COMMENT '创建人',
	create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_by VARCHAR(100) COMMENT '修改人',
	update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间'
) COMMENT '待办事项管理表';